# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='movie_genre',
            new_name='movie_type',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='movie_release_date',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        )
    ]
