# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0003_movieinfo_movie_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_test', models.CharField(max_length=200)),
            ],
        ),
    ]
